- .gitignore
- package-lock.json
- package.json
> this is the file structure

- .prettierrc
- .vscode/settings.json
created .prettierrc
created workspace vscode settings to format on save, and use prettier as default formatter
> prettier config

- js/xhr.js
i create the xhr file and i write inside it api function and update it to es6 ,
Relates #4
> 4 xhr function

- README.md
- index.html
> Create the HTML layout

- package.json
- test/test.js
> install jest

- index.html
- js/dom.js
- style/style.css
* I've added "Search button" to the HTML layout.
* Customize search input and search button in css.
* Call search input and button in the dom.js file and create an eventlistener for the search button that console.log what is written at the search input.
Relates #6
> Add search button and style search input

- index.html
- js/logic.js
> Applied time and greeting

- .gitignore
- index.html
- js/dom.js
- js/xhr.js
- style/style.css
i solve the conflict and add the background for what you search and add function named changebackground
> 8 unsplash api

- style/style.css
i change css background to change background every refresh
> change background by default when refresh #20

- index.html
- js/dom.js
- js/logic.js
- package-lock.json
- package.json
- style/style.css
- test/test.js
created a function called greeting to test weather it's morning time or evening time 
also made a function to add greeting, time and date on the page 
relates #11
> created greeting function with its tests

- js/dom.js
relates #25
refactored the code that displays the greeting, time and date
> code refactored

- index.html
- style/style.css
i make some change on button and the search input and some change on html file like put it in main and sections
> Styling search

- index.html
- style/style.css
> 9 styling index

- index.html
- js/dom.js
Showing the temperature at the page using dom.
> Dom the temperature

- js/dom.js
i create a function change background every 5 sec #36 review it .
> creat function change background every 5 sec #36

- index.html
- js/dom.js
- style/style.css
> fixed some styles to make the page responsive

- style/style.css
> solve THE style last minute  #36

- package.json
> Update project name in json file

- js/dom.js
> fixedd time

- js/dom.js
- js/logic.js
- js/xhr.js
> Fix return in arrow functions and use strict equal

- index.html
- js/dom.js
- js/xhr.js
- package-lock.json
- package.json
- style/style.css
i fix the css file and xhr file review it
> worked on issues for mentors #43 #44 #54
